name: Test first 50 polynomials

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  test-polynomials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - name: "HOMFLY Polynomial - Knots"
            command: "python check_knotinfo.py --polynomial P --knots -c 50"
          - name: "Kauffman Polynomial - Knots"
            command: "python check_knotinfo.py --polynomial F --knots -c 50"
          - name: "Kauffman Polynomial - Links"
            command: "python check_knotinfo.py --polynomial F --links -c 50"
      fail-fast: false
    
    name: ${{ matrix.test-case.name }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run polynomial test
      run: |
        output=$(uv run ${{ matrix.test-case.command }})
        echo "$output"
        if echo "$output" | grep -q "Wrong"; then
          echo "❌ Test failed: Found incorrect polynomial calculations"
          exit 1
        else
          echo "✅ Test passed: All polynomial calculations are correct"
        fi
      timeout-minutes: 30
