name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: ./report/main.typ

      - name: Update artifact name
        run: cp ./report/main.pdf ./report/kauffman-polynomial-report.pdf
  
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ./report/kauffman-polynomial-report.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: ./report/kauffman-polynomial-report.pdf
